SELECT ?item ?itemLabel ?value ?website WHERE {
  {
    SELECT ?item (MAX(?v) AS ?value) (SAMPLE(?site) AS ?website) WHERE {
      ?item wdt:P31 wd:Q1248784 ;
            wdt:P17 wd:Q142 ;
            wdt:P2044 ?v .
      FILTER(?v > 200)
      OPTIONAL { ?item wdt:P856 ?site . }
    }
    GROUP BY ?item
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
ORDER BY DESC(?value) ?item
LIMIT 20
